#!/usr/bin/env python3
"""
Добавление Audit Trail Page в подписанный PDF
Запускается как PostgreSQL триггер или cron job
"""

import sys
import base64
import psycopg2
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from PyPDF2 import PdfReader, PdfWriter
import io

# Database connection
DB_CONFIG = {
    'host': '72.62.114.139',
    'port': '5432',
    'database': 'documenso',
    'user': 'documenso',
    'password': 'documenso123'
}

def create_audit_trail_page(audit_logs):
    """Создает PDF страницу с audit trail"""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # Заголовок
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, height - 2*cm, "AUDIT TRAIL")
    
    # Линия под заголовком
    c.line(2*cm, height - 2.5*cm, width - 2*cm, height - 2.5*cm)
    
    # Описание
    c.setFont("Helvetica", 10)
    c.drawString(2*cm, height - 3.5*cm, "This page contains a detailed audit trail of all actions performed on this document.")
    
    # События
    y = height - 5*cm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, y, "Document Events")
    y -= 0.8*cm
    
    c.setFont("Helvetica", 9)
    for log in audit_logs:
        if y < 3*cm:  # Новая страница если места нет
            c.showPage()
            y = height - 2*cm
            c.setFont("Helvetica", 9)
        
        # Тип события
        c.setFont("Helvetica-Bold", 9)
        c.drawString(2*cm, y, f"• {log['type'].replace('_', ' ')}")
        y -= 0.5*cm
        
        # Детали
        c.setFont("Helvetica", 8)
        c.drawString(3*cm, y, f"Date/Time: {log['created_at']}")
        y -= 0.4*cm
        
        if log.get('name'):
            c.drawString(3*cm, y, f"Signer: {log['name']} ({log['email']})")
            y -= 0.4*cm
        
        y -= 0.3*cm  # Отступ между событиями
    
    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(2*cm, 2*cm, f"Generated by Documenso on {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    c.drawString(2*cm, 1.5*cm, "This audit trail is cryptographically signed and tamper-evident.")
    
    c.save()
    buffer.seek(0)
    return buffer

def get_audit_logs(conn, envelope_id):
    """Получает audit logs для envelope"""
    cursor = conn.cursor()
    
    # Получаем audit logs с деталями recipients
    query = """
        SELECT 
            dal.type,
            dal."createdAt",
            r.name,
            r.email,
            r."signingStatus",
            r.role
        FROM "DocumentAuditLog" dal
        LEFT JOIN "Recipient" r ON dal."envelopeId" = r."envelopeId"
        WHERE dal."envelopeId" = %s
        ORDER BY dal."createdAt" ASC
    """
    
    cursor.execute(query, (envelope_id,))
    rows = cursor.fetchall()
    
    logs = []
    for row in rows:
        logs.append({
            'type': row[0],
            'created_at': row[1].strftime('%Y-%m-%d %H:%M:%S UTC'),
            'name': row[2],
            'email': row[3],
            'signing_status': row[4],
            'role': row[5]
        })
    
    return logs

def add_audit_trail_to_pdf(envelope_id):
    """Добавляет audit trail page в PDF документ"""
    conn = psycopg2.connect(**DB_CONFIG)
    
    try:
        # Получаем audit logs
        audit_logs = get_audit_logs(conn, envelope_id)
        
        if not audit_logs:
            print(f"No audit logs found for envelope {envelope_id}")
            return False
        
        # Получаем оригинальный PDF
        cursor = conn.cursor()
        query = """
            SELECT dd.data, dd.id, ei.id
            FROM "Envelope" e
            JOIN "EnvelopeItem" ei ON e.id = ei."envelopeId"
            JOIN "DocumentData" dd ON dd.id = ei."documentDataId"
            WHERE e.id = %s
            LIMIT 1
        """
        
        cursor.execute(query, (envelope_id,))
        row = cursor.fetchone()
        
        if not row:
            print(f"No document data found for envelope {envelope_id}")
            return False
        
        pdf_base64, data_id, item_id = row
        
        # Декодируем PDF
        pdf_bytes = base64.b64decode(pdf_base64)
        
        # Читаем оригинальный PDF
        original_pdf = PdfReader(io.BytesIO(pdf_bytes))
        
        # Создаем audit trail page
        audit_page_buffer = create_audit_trail_page(audit_logs)
        audit_pdf = PdfReader(audit_page_buffer)
        
        # Объединяем
        writer = PdfWriter()
        
        # Добавляем все страницы оригинального PDF
        for page in original_pdf.pages:
            writer.add_page(page)
        
        # Добавляем audit trail pages
        for page in audit_pdf.pages:
            writer.add_page(page)
        
        # Сохраняем в buffer
        output_buffer = io.BytesIO()
        writer.write(output_buffer)
        output_buffer.seek(0)
        
        # Кодируем обратно в base64
        new_pdf_base64 = base64.b64encode(output_buffer.read()).decode('utf-8')
        
        # Обновляем в БД
        update_query = """
            UPDATE "DocumentData"
            SET data = %s
            WHERE id = %s
        """
        
        cursor.execute(update_query, (new_pdf_base64, data_id))
        conn.commit()
        
        print(f"✅ Audit trail page added to envelope {envelope_id}")
        return True
        
    except Exception as e:
        print(f"❌ Error adding audit trail: {e}")
        conn.rollback()
        return False
    finally:
        conn.close()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 add_audit_trail.py <envelope_id>")
        sys.exit(1)
    
    envelope_id = sys.argv[1]
    success = add_audit_trail_to_pdf(envelope_id)
    sys.exit(0 if success else 1)
