SELECT id, "createdAt", type, "ipAddress", "userAgent"
FROM "DocumentAuditLog"
WHERE type IN ('DOCUMENT_COMPLETED', 'RECIPIENT_SIGNED', 'DOCUMENT_SIGNED', 'ENVELOPE_SIGNED', 'RECIPIENT_COMPLETED', 'ENVELOPE_COMPLETED', 'FIELD_SIGNED')
ORDER BY id DESC
LIMIT 20;
